{% set name = "pymablock" %}
{% set version = "2.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 5befc09fe984c3a235da11f2d051fefcde987cf1ef425c30451cd3f8476954d8

build:
  script: {{ PYTHON }} -m pip install . --no-deps -vv
  noarch: python
  number: 0

requirements:
  host:
    - python >=3.9
    - pip
    - hatchling
    - hatch-vcs
  run:
    - python >=3.9
    - numpy >=1.23
    - scipy >=1.8
    - sympy >=1.10
    - python-mumps >=0.0.1,<0.1
    - packaging >=22.0

test:
  imports:
    - pymablock

about:
  home: https://pymablock.readthedocs.io/
  summary: 'Quasi-degenerate perturbation theory in Python'
  description: |
    Pymablock is a Python package for quasi-degenerate perturbation theory
    calculations. It handles symbolic, dense and sparse calculations, and
    implements arbitrary order multivariate perturbations.
  license: BSD-2-Clause
  license_family: BSD
  license_file: LICENSE
  doc_url: https://pymablock.readthedocs.io/
  dev_url: https://gitlab.kwant-project.org/qt/pymablock

extra:
  recipe-maintainers:
    - akhmerov
    - iarayad
