schema_version: 1

context:
  name: pymablock
  version: 2.2.0
  python_min: 3.11

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/${{ name }}-${{ version }}.tar.gz
  sha256: a35804c6c9f53ddf47849fef189ffafc0e0639d9261154fe9a8d56afcd3320f0

build:
  number: 1
  noarch: python
  script: ${{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python 3.11.*
    - pip
    - hatchling
    - hatch-vcs
  run:
    - python >=${{ python_min }}
    - numpy >=1.26
    - scipy >=1.12
    - sympy >=1.13
    - python-mumps >=0.0.1,<0.1
    - packaging >=22.0

tests:
  - python:
      imports:
        - pymablock
      pip_check: false
      python_version: ${{ python_min }}.*
about:
  summary: Quasi-degenerate perturbation theory in Python
  description: |
    Pymablock is a Python package for quasi-degenerate perturbation theory
    calculations. It handles symbolic, dense and sparse calculations, and
    implements arbitrary order multivariate perturbations.
  license: BSD-2-Clause
  license_file: LICENSE
  homepage: https://pymablock.readthedocs.io/
  repository: https://gitlab.kwant-project.org/qt/pymablock
  documentation: https://pymablock.readthedocs.io/

extra:
  recipe-maintainers:
    - akhmerov
    - iarayad
